#!/bin/bash
python generate_controllers.py -e Swimmer -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10  
python validate_controllers.py -e Swimmer -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10  
python validate_generalization.py -e Swimmer -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10 
python generate_controllers.py -e Humanoid -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10  
python validate_controllers.py -e Humanoid -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10  
python validate_generalization.py -e Humanoid -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10 
python generate_controllers.py -e Hopper -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10  
python validate_controllers.py -e Hopper -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10  
python validate_generalization.py -e Hopper -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10 
python generate_controllers.py -e Walker2d -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10 
python validate_controllers.py -e Walker2d -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10 
python validate_generalization.py -e Walker2d -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10 
python generate_controllers.py -e Swimmer -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10  
python validate_controllers.py -e Swimmer -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10  
python validate_generalization.py -e Swimmer -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10 
python generate_controllers.py -e Ant -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10 
python validate_controllers.py -e Ant -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10 
python validate_generalization.py -e Ant -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10 
python generate_controllers.py -e Hopper -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10  
python validate_controllers.py -e Hopper -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10  
python validate_generalization.py -e Hopper -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10 
python generate_controllers.py -e Walker2d -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10 
python validate_controllers.py -e Walker2d -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10 
python validate_generalization.py -e Walker2d -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10 
python generate_controllers.py -e Ant -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10 
python validate_controllers.py -e Ant -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10 
python validate_generalization.py -e Ant -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10 
python generate_controllers.py -e Humanoid -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10  
python validate_controllers.py -e Humanoid -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10  
python validate_generalization.py -e Humanoid -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10 
python generate_controllers.py -e Hopper -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10  
python validate_controllers.py -e Hopper -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10  
python validate_generalization.py -e Hopper -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10 
python generate_controllers.py -e Walker2d -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10 
python validate_controllers.py -e Walker2d -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10 
python validate_generalization.py -e Walker2d -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10 
python generate_controllers.py -e HalfCheetah -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10  
python validate_controllers.py -e HalfCheetah -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10  
python validate_generalization.py -e HalfCheetah -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10 
python generate_controllers.py -e Ant -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10 
python validate_controllers.py -e Ant -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10 
python validate_generalization.py -e Ant -c probabilistic -r PAC_Bayes -elec 0 -MC 10 -pbn 10 
python generate_controllers.py -e HalfCheetah -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10  
python validate_controllers.py -e HalfCheetah -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10  
python validate_generalization.py -e HalfCheetah -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10 
python generate_controllers.py -e Humanoid -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10  
python validate_controllers.py -e Humanoid -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10  
python validate_generalization.py -e Humanoid -c probabilistic -r PAC_Bayes -elec 12 -MC 10 -pbn 10 
python generate_controllers.py -e Swimmer -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10  
python validate_controllers.py -e Swimmer -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10  
python validate_generalization.py -e Swimmer -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10 
python generate_controllers.py -e HalfCheetah -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10  
python validate_controllers.py -e HalfCheetah -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10  
python validate_generalization.py -e HalfCheetah -c probabilistic -r PAC_Bayes -elec 6 -MC 10 -pbn 10 